server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:

        # USER SERVICE
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        # WALLET SERVICE  ✅ ADD THIS
        - id: wallet-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/wallets/**

        # TRANSACTION SERVICE
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/transactions/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        # REWARD SERVICE
        - id: reward-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/rewards/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        # NOTIFICATION SERVICE
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG